#!/bin/bash

if [ -z ${BASE_DIR+x} ]; 
then 
	BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd );
fi

CLASSPATH="$CLASSPATH;$BASE_DIR/target/perftools-0.0.1-SNAPSHOT-jar-with-dependencies.jar"

java -cp $CLASSPATH org.speedd.perf.TransactionEventGenerator $@